### ISSUE TITLE
[Bug]: v_rising_bepinex

### ISSUE THREAD

**Issue by nixmomo** [pelican-eggs/games-steamcmd#111]
### Panel Version

1.11.10

### Wings Version

1.11.13

### Service

https://github.com/pelican-eggs/games-steamcmd/tree/main/v_rising/v_rising_bepinex

### Modified

No, I did not modify the egg

### Expected Behavior

A working Server installed with Bepinex

### Actual Behavior

Bepinex is not installed properly.... the "dotnet" Folder is missing in total... it needs to be manual uploaded and that should be done in the installation

### Steps To Reproduce

import the egg with bepinex
install the server 
look into server root of container and you see there is no dotnet folder

### Install logs

not needed

**Comment by QuintenQVD0** [comment]
no install logs means we can not help

**Comment by nixmomo** [comment]
[install.txt](https://github.com/user-attachments/files/18246722/install.txt)
yeah it would be to easy to install a server on your machine right? anyway here is the log from console after installing it and here a picture of folder structure what is created
![image](https://github.com/user-attachments/assets/5b1335c1-a5d5-4fe9-954d-bde74bd1b374)

**Comment by QuintenQVD0** [comment]
@gOOvER This seems something for you.

**Comment by gOOvER** [comment]
why should there a dotnet dir? As i remember, there was never any dotnet dir

**Comment by nixmomo** [comment]
is this question serious? bepinex is not working without this dir, the doorcloser is also expecting this dir... bepinex is not loading any of the plugin without it.. Do you ever tested this server?  
at least a minimum from this file is needed dotnet\coreclr.dll and all it dependencies.... this file is mentioned in the doorstop_config.ini

**Comment by gOOvER** [comment]
> Do you ever tested this server? 
i wrote this server ;)

**Comment by nixmomo** [comment]
I know that not all plugins are working and that it runs on wine but i tested it with some mods and with the dotnet folder the plugins are loading correctly.. without it bepinex is not working in total.
Removing the line has worked for a new server without my workaroung with reupload the dotnet folder.



> i wrote this server ;)

cool but how has any plugin worked without this folder? if you deleted it and shows the startup log you can see that it has never worked and bepinex was never loaded before :D
