### ISSUE TITLE
[Egg Request]: Soulmask

### ISSUE THREAD

**Issue by Simpuhl** [pelican-eggs/games-steamcmd#115]
### Does this expand an already existing service

Yes

### Link to a game or software

https://mask.qoolandgames.com/

### Links for the download

steamcmd +login anonymous +app_update 3017300 validate +quit

### Links for the install docs

https://soulmask.fandom.com/wiki/Private_Server

**Comment by Simpuhl** [comment]
As far as I know the only way to dl the server is using the command I posted above, sorry I didn't find any links...

Also, that fandom page is written by the developer as you can see in this post: https://steamcommunity.com/app/2646460/discussions/0/4330853251139833199/

**Comment by gOOvER** [comment]
Stop beeing lazy and start searching the repo:

https://github.com/pelican-eggs/games-steamcmd/tree/main/soulmask

**Comment by Simpuhl** [comment]
> Stop beeing lazy and start searching the repo., Its annoying, when people are lazy and dont look for their own.
> 
> https://github.com/pelican-eggs/games-steamcmd/tree/main/soulmask

I literally just came to reply that I found it. Funny I was searching last night via mobile and I didn't see it but I found it easily on my desktop. https://github.com/pelican-eggs/games-steamcmd/tree/main/soulmask

my bad

**Comment by gOOvER** [comment]
can be closed

**Comment by QuintenQVD0** [comment]
Closed. If you want to search in files you must be loged in.
