### ISSUE TITLE
[Egg Request]: Farming Simulator 2022

### ISSUE THREAD

**Issue by jojolebobo** [pelican-eggs/games-steamcmd#22]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/wine-gameservers/arch-wine-fs22/?tab=readme-ov-file#initial-installation

### Links for the download

https://github.com/wine-gameservers/arch-wine-fs22/

### Links for the install docs

https://github.com/wine-gameservers/arch-wine-fs22/

**Comment by QuintenQVD0** [comment]
Has been asked multiple times in the dc and in request in the old repo. Answer is still no not possible. I send 2 full weeks with toetje (ower of that repo you linked) and it can not be done.
