### ISSUE TITLE
[Egg Request]: Soulmask

### ISSUE THREAD

**Issue by Northwave** [pelican-eggs/games-steamcmd#31]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/2646460/Soulmask/

### Links for the download

https://steamdb.info/app/3017310/info/

### Links for the install docs

https://soulmask.fandom.com/wiki/Private_Server

**Comment by QuintenQVD0** [comment]
https://github.com/pelican-eggs/games-steamcmd/tree/main/soulmask

already added some days ago?
