### ISSUE TITLE
[Bug]: Arma Reforger

### ISSUE THREAD

**Issue by hafometh88** [pelican-eggs/games-steamcmd#44]
### Panel Version

1.11.7

### Wings Version

1.11.13

### Service

Arma Reforger

### Modified

No, I did not modify the egg

### Expected Behavior

Changing the `VISIBLE` variable should change the game config's `visible` key to `true` or `false`, depending on what is set to the variable

Changing the `ENABLE_THIRD` variable should change the game config's `visible` key to `true` or `false`, depending on what is set to the variable

### Actual Behavior

The config does not reflect any changes to the `VISIBLE` variable

The config does not reflect any changes to the `DISABLE_THIRD` variable

### Steps To Reproduce

1. Check if the game's config has the `disableThirdPerson` or `visible` key set to `true`
2. Go ahead and change the `DISABLE_THIRD` or `VISIBLE` variable to `false`
3. Start the server
4. Check the game's config again, no changes were made to `disableThirdPerson` or `visible` key

### Install logs

not needed

**Comment by gOOvER** [comment]
is not pe parsed,, so the variable is more or lesser useless. Change it by hand

```
{
    "config.json": {
        "parser": "json",
        "find": {
            "bindAddress": "0.0.0.0",
            "bindPort": "{{server.allocations.default.port}}",
            "publicAddress": "{{server.allocations.default.ip}}",
            "publicPort": "{{server.allocations.default.port}}",
            "game.name": "{{server.environment.SERVER_NAME}}",
            "game.password": "{{server.environment.SERVER_PASS}}",
            "game.passwordAdmin": "{{server.environment.ADMIN_PASS}}",
            "game.scenarioId": "{{server.environment.SCENARIO_ID}}",
            "game.maxPlayers": "{{server.environment.MAX_PLAYERS}}",
            "game.gameProperties.fastValidation": true
        }
    }
}
```

**Comment by hafometh88** [comment]
> Is not parsed, so the variable is more or lesser useless. Change it by hand or add the parsing
> 
> ```
> {
>     "config.json": {
>         "parser": "json",
>         "find": {
>             "bindAddress": "0.0.0.0",
>             "bindPort": "{{server.allocations.default.port}}",
>             "publicAddress": "{{server.allocations.default.ip}}",
>             "publicPort": "{{server.allocations.default.port}}",
>             "game.name": "{{server.environment.SERVER_NAME}}",
>             "game.password": "{{server.environment.SERVER_PASS}}",
>             "game.passwordAdmin": "{{server.environment.ADMIN_PASS}}",
>             "game.scenarioId": "{{server.environment.SCENARIO_ID}}",
>             "game.maxPlayers": "{{server.environment.MAX_PLAYERS}}",
>             "game.gameProperties.fastValidation": true
>         }
>     }
> }
> ```

Thank you. I figured this out by my own, but this should probably be changed in the egg, because it does not really make sense to include it if it does not work, it just creates confusion for users.

**Comment by gOOvER** [comment]
yeah, its a "bug" in the egg.

**Comment by lilkingjr1** [comment]
@hafometh88 Agreed; sorry for the confusion. I vaguely remember figuring out that the visible setting is possibly useless because it may make the server unable to connect to, and it's possible I just forgot to take out the variable. As for the `DISABLE_THIRD` variable, it looks like it's set during install but not on subsequent boots. I'll try to fix these issues soon. Thanks for the Issue report!

**Comment by hafometh88** [comment]
@lilkingjr1 Thank you very much!

> I vaguely remember figuring out that the visible setting is possibly useless because it may make the server unable to connect to, and it's possible I just forgot to take out the variable.

It might have been a bug in some previous versions, but now it works fine. I use it to hide my servers all the time. You have to manually connect via IP and port, but it works alright, no issues there.

**Comment by lilkingjr1** [comment]
Fix pending review. Please test the above PR and leave a review if it works for you.

**Comment by hafometh88** [comment]
@lilkingjr1 Thank you very much for the fixes. I can confirm all works as intended now.
