### ISSUE TITLE
[Egg Request]: Steamcmd tmodlauncher

### ISSUE THREAD

**Issue by Draakoor** [pelican-eggs/games-steamcmd#48]
### Does this expand an already existing service

Yes

### Link to a game or software

https://store.steampowered.com/app/1281930/tModLoader/

### Links for the download

https://github.com/tModLoader/tModLoader/wiki/Starting-a-modded-server

### Links for the install docs

https://github.com/tModLoader/tModLoader/wiki/Starting-a-modded-server

Adds automatic installation for mods via workshop

**Comment by QuintenQVD0** [comment]
Already there. Just in the standalone repo: https://github.com/pelican-eggs/games-standalone/tree/main/terraria/tmodloader
