### ISSUE TITLE
[Bug]: V-Rising server does not work

### ISSUE THREAD

**Issue by Coniface** [pelican-eggs/games-steamcmd#56]
### Panel Version

1.11.7

### Wings Version

1.11.13

### Service

v_rising/v_rising_vanilla

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, start it, play

### Actual Behavior

The server installation claims to be completed but when I try to run the server, I get an error with wine which could not find kernel32.dll.
```
First launch will throw some errors. Ignore them
:/home/container$ wine ./VRisingServer.exe -address 0.0.0.0 -gamePort ${SERVER_PORT} -persistentDataPath save-data
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
wine: could not load kernel32.dll, status c0000135
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 53
[Pterodactyl Daemon]: Out of memory: false
```

I tried reinstalling from scratch many times, also with bepinex version.
I tried deleting `.cache` and `.wine` directories and restart, no difference.

### Steps To Reproduce

- Download [latest egg version](https://github.com/pelican-eggs/games-steamcmd/blob/main/v_rising/v_rising_vanilla/egg-pterodactyl-v-rising.json)
- Import Egg in Pterodactyl
- Create new server using this egg and default params
- Installation completes
- Server attempts to start

Here it might stay "up" for a very long time (it appears orange in the servers list) but nothing works. If you try and connect, it doesn't work.
Eventually, the server restarts 2 times and crashes straight away.
From there on, it's impossible to start it as the error repeats straight away.

### Install logs

https://ptero.co/wolarobawo

**Comment by gOOvER** [comment]
pls post the output of:

`hostnamectl status`

**Comment by gOOvER** [comment]
[egg-pterodactyl-v-rising.json](https://github.com/user-attachments/files/16471522/egg-pterodactyl-v-rising.json)

Please test this egg. Its for Ptero. 

1. update the egg
2. delete .wine and .cache
3. run reinstall
4. start server

**Comment by gOOvER** [comment]
Do you have consoleoutput without the modification?

**Comment by lilkingjr1** [comment]
I can confirm I have the same issue with a newly installed server (install is successful without error). Console output of startup below:
```
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Status: Image is up to date for ghcr.io/parkervcp/yolks:wine_staging 
Digest: sha256:e47f333bdd0c3550d5fe1889912dcbdec64f65fcf48e9edb6c37bd9f910458f0 
[Pterodactyl Daemon]: Finished pulling Docker container image
Running on Debian 12.6
Current timezone: Etc/UTC
wine-9.13 (Staging)
steam user is not set.
Using anonymous user.
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
Logging directory: '/home/container/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1721172922
-- type 'quit' to exit --
Loading Steam API...OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
"@sSteamCmdForcePlatformType" = "windows"
Success! App '1829350' already up to date.
Success! App '1007' already up to date.
First launch will throw some errors. Ignore them
:/home/container$ wine ./VRisingServer.exe -address 0.0.0.0 -gamePort ${SERVER_PORT} -persistentDataPath save-data
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
wine: could not load kernel32.dll, status c0000135
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 53
[Pterodactyl Daemon]: Out of memory: false
```

Changing the image to `wine_stable` does seem to resolve the issue, and it honestly should be on stable anyways if it can (I think `wine_staging` might have been needed for pre-1.0 early access servers, but that's not the case anymore).

Thank you for the find and report @Coniface. Once I finish up some testing, I'll submit a PR to fix this.

**Comment by lilkingjr1** [comment]
@gOOvER Do you want me to update the BepInEx Egg too?
