### ISSUE TITLE
[Install Bug]: <foundry>

### ISSUE THREAD

**Issue by itobin** [pelican-eggs/games-steamcmd#63]
### Panel Version

1.11.7

### Wings Version

1.11.13

### Service

foundry

### Modified

No, I did not modify the egg

### Expected Behavior

Server should start up

### Actual Behavior

Server installs, however when starting the server is errors with

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
"@sSteamCmdForcePlatformType" = "windows"
Success! App '2915550' already up to date.
Success! App '1007' already up to date.
First launch will throw some errors. Ignore them
Installing mono
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
wine: could not load kernel32.dll, status c0000135
:/home/container$ xvfb :0 -screen 0 1024x768x16; DISPLAY=:0.0 xvfb-run wine /home/container/FoundryDedicatedServer.exe -log
/entrypoint.sh: line 90: xvfb: command not found
wine: could not load kernel32.dll, status c0000135
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 53
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago

### Steps To Reproduce

Install a Foundry server

### Install logs

https://ptero.co/kedebabisu

**Comment by QuintenQVD0** [comment]
What image is this egg using ? and is this lxc, or unraid hosted?
