### ISSUE TITLE
[Egg Request]: <Dawn of Defiance>

### ISSUE THREAD

**Issue by Off-Load** [pelican-eggs/games-steamcmd#64]
### Does this expand an already existing service

No

### Link to a game or software

https://www.dawnofdefiance.com/

### Links for the download

https://store.steampowered.com/app/2059530/Dawn_of_Defiance/

### Links for the install docs

https://store.epicgames.com/en-US/p/dawn-of-defiance-b4f0ca

**Comment by Off-Load** [comment]
Dawn of Defiance launched Aug.15 and is an multiplayer game, but the devs is hesitated to release dedicated server, only 4 player/playerhosted server is available right now.
Is it possible to make an egg for this game?

**Comment by ImKringle** [comment]
player hosted server = not eggable

**Comment by Off-Load** [comment]
> player hosted server = not eggable, what theyre using is Peer2Peer - not a dedicated server

Ok. Thanks, good to know for other games :)

**Comment by QuintenQVD0** [comment]
I am closing this as Peer2Peer is not a dedicated server and not possible
