### ISSUE TITLE
[Egg Request]: Wreckfest

### ISSUE THREAD

**Issue by CBADavid** [pelican-eggs/games-steamcmd#71]
### Does this expand an already existing service

Yes

### Link to a game or software

https://store.steampowered.com/app/228380/Wreckfest/

### Links for the download

https://store.steampowered.com/app/228380/Wreckfest/

### Links for the install docs

https://steamcommunity.com/app/228380/discussions/0/613938693082657261/

**Comment by QuintenQVD0** [comment]
Unless something changed: https://github.com/pelican-eggs/eggs/issues/1107
