### ISSUE TITLE
[Egg Request]: Satisfactory v1.0 Release 9/10

### ISSUE THREAD

**Issue by Kuroo2021** [pelican-eggs/games-steamcmd#73]
### Does this expand an already existing service

Yes

### Link to a game or software

https://www.satisfactorygame.com/

### Links for the download

https://steamdb.info/app/1690800/

### Links for the install docs

https://satisfactory.wiki.gg/wiki/Dedicated_servers/Configuration_files

**Comment by lilkingjr1** [comment]
Please read the current Egg's README and be patient. It will be updated sometime today.

**Comment by ValhallaCommunityOfficial** [comment]
Probably already known but they're having some issues atm
https://github.com/wolveix/satisfactory-server/issues/260
