### ISSUE TITLE
[Bug]: <Egg Name>Satisfactory

### ISSUE THREAD

**Issue by blue808** [pelican-eggs/games-steamcmd#89]
### Panel Version

1.11.7.1

### Wings Version

1.11.14.0

### Service

Satisfactory

### Modified

No, I did not modify the egg

### Expected Behavior

![image](https://github.com/user-attachments/assets/d2086c4c-20d8-45be-974a-0b4205685184)
Adding a player to the server will increase CPU utilization，There are only 2 players in the screenshot。

### Actual Behavior

Is this an egg problem or a game server problem

### Steps To Reproduce

![image](https://github.com/user-attachments/assets/b07f7604-4ca8-40c8-b182-a1938bd413bb)

### Install logs

Not yet

**Comment by QuintenQVD0** [comment]
This is a problem that the game devs have to fixt. With 1.0 the server now demands way more resources.

**Comment by gOOvER** [comment]
2 cores are too less for satisfactory
