### ISSUE TITLE
[Eco]: Bad `INSTALL_FLAGS` Variable Default Value

### ISSUE THREAD

**Issue by itobin** [pelican-eggs/games-steamcmd#90]
### Panel Version

1.11.7

### Wings Version

1.11.13

### Service

Eco

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, then start up.

### Actual Behavior

Server crashes with error

[Pterodactyl Daemon]: Finished pulling Docker container image
steam user is not set.
Using anonymous user.
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
Logging directory: '/home/container/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1726605427
-- type 'quit' to exit --
Loading Steam API...OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Success! App '1007' already up to date.
ERROR! Failed to set beta 'default'
:/home/container$ ./EcoServer
/entrypoint.sh: line 89: ./EcoServer: No such file or directory
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...

### Steps To Reproduce

Step 1: Install the game via the egg
Step 2: Start the server

### Install logs

https://ptero.co/isivicuwuh

**Comment by lilkingjr1** [comment]
@gOOvER The README states you are the author of this Egg. If you would like to fix it, `INSTALL_FLAGS` default value is set to "-beta default" and SteamCMD doesn't like this beta branch name now. Also, your Installation Script allows the use of `SRCDS_BETAID`, which I think would be cleaner to use in this scenario if you need to specify a beta branch.

**Comment by gOOvER** [comment]
@QuintenQVD0 have allready a fixed Egg, AS i know

**Comment by itobin** [comment]
FYI this isnt fixed, ive just downloaded it and its still same issue.

**Comment by gOOvER** [comment]
> @gOOvER @QuintenQVD0  FYI this isnt fixed, ive just downloaded it and its still same issue.
> 
> IPC function call IClientAppManager::GetUpdateInfo took too long: 188 msec
> Success! App '1007' fully installed.
> ERROR! Failed to set beta 'default'
> :/home/container$ ./EcoServer
> /entrypoint.sh: line 89: ./EcoServer: No such file or directory

check m repo for a working egg, If you want IT fast

**Comment by lilkingjr1** [comment]
> ERROR! Failed to set beta 'default'

@itobin The new Egg does not tell SteamCMD to set the beta to 'default' at all, so I don't believe your Egg is properly updated. I would delete your old Egg, upload the new one, and make the server instance from scratch.

**Comment by QuintenQVD0** [comment]
> @gOOvER @QuintenQVD0  FYI this isnt fixed, ive just downloaded it and its still same issue.
> 
> IPC function call IClientAppManager::GetUpdateInfo took too long: 188 msec
> Success! App '1007' fully installed.
> ERROR! Failed to set beta 'default'
> :/home/container$ ./EcoServer
> /entrypoint.sh: line 89: ./EcoServer: No such file or directory

Looking at you startup you updated the egg and an already made server. So your startup is not changed and the wrong values are in the variables. So fix both as it does work.

**Comment by QuintenQVD0** [comment]
And this was not needed Goover!

This egg is litterly a coppy of yours as I told you in your dm. He updated it wrong. So instad of direct pointing to your own repo try by giving some help first!

> > @gOOvER @QuintenQVD0  FYI this isnt fixed, ive just downloaded it and its still same issue.
> > 
> > IPC function call IClientAppManager::GetUpdateInfo took too long: 188 msec
> > Success! App '1007' fully installed.
> > ERROR! Failed to set beta 'default'
> > :/home/container$ ./EcoServer
> > /entrypoint.sh: line 89: ./EcoServer: No such file or directory
> 
> check m repo for a working egg, If you want IT fast
> 
> https://github.com/gsrvtech/gameserver-templates/tree/main/steamcmd-games/eco

**Comment by gOOvER** [comment]
i dont see, that its not allowed to post other repos. 

it was faster for me posting a working egg.

**Comment by QuintenQVD0** [comment]
> i dont see, that its not allowed to post other repos.
> 
> it was faster for me posting a working egg.

This one works to, as it is literly based on your and you know that, instad of giving help just pointing to somewhere else is not what this repo is for. As I know you know eggs very well so if you had looked for 2+ seconds you would have been able to resolve this to point to your own repo

**Comment by itobin** [comment]
@gOOvER @QuintenQVD0 @lilkingjr1 after competely removing the egg and re adding, this is now working.  thanks for the help.
