### ISSUE TITLE
bug: conan exiles egg server not reachable

### ISSUE THREAD

**Issue by Dequalix** [pelican-eggs/games-steamcmd#92]
### Panel Version

1.11.7

### Wings Version

1.11.13

### Service

steamcmd/conan_exiles

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, server runs and its online.

### Actual Behavior

Server installs the game files, when it runs, nothing, looks like its not connected to the server console.
 I checked if the server did go up anyways, but it hasnt
```
Executing cd /home/container
Executing cabextract -q -d /home/container/.wine/dosdevices/c:/windows/temp /home/container/.cache/winetricks/corefonts/webdin32.exe
------------------------------------------------------
warning: Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/home/container/.wine terminate
------------------------------------------------------
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing wine64 C:\windows\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing cp /home/container/.wine/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.V9tSl6JE/_reg_405b24a4_2039.reg
Executing wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing wine64 C:\windows\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing cp /home/container/.wine/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.V9tSl6JE/_reg_70fc14d8_2039.reg
:/home/container$ xvfb-run --auto-servernum wine /home/container/ConanSandbox/Binaries/Win64/ConanSandboxServer-Win64-Shipping.exe -Port=${SERVER_PORT} -QueryPort=${QUERY_PORT} -RconPort=${RCON_PORT} -ServerName="${SRV_NAME}" -ServerPassword="${SRV_PW}" -console -log
```

Here its stuck. 

Edit:
The server does start, i can see that in the logs, but its in now way reachable. Sorry im a bit clueless with this. so idk how to fix this issue. I allocated all the used ports, but none are reachable for some reason.

### Steps To Reproduce

Import the egg: [egg-conan-exiles.json](https://github.com/pelican-eggs/games-steamcmd/blob/main/conan_exiles/egg-conan-exiles.json)
Create a server
Run the server.

### Install logs

https://ptero.co/ipomagokij

**Comment by QuintenQVD0** [comment]
It is running. There is just no console output with wine anymore.

**Comment by Dequalix** [comment]
> It is running. There is just no console output with wine anymore.

okay i can tell it is using resources, but i cant reach the server at all.

**Comment by QuintenQVD0** [comment]
> > It is running. There is just no console output with wine anymore.
> 
> okay i can tell it is using resources, but i cant reach the server at all. (i tried local ip as wel as remote, the ports are open ofc.) besides, if i run it, it keeps showing yellow, its not flagged as running.

Thatq because the console output does not work so it can never be marked as running.

**Comment by QuintenQVD0** [comment]
You allocated all 4 ports?

**Comment by Dequalix** [comment]
Yes, tried connecting even on rcon tool. Its just not availible
