### ISSUE TITLE
[Install Bug]: <Portal Knights>

### ISSUE THREAD

**Issue by itobin** [pelican-eggs/games-steamcmd#96]
### Panel Version

1.11.7

### Wings Version

1.11.13

### Service

Portal Knights

### Modified

No, I did not modify the egg

### Expected Behavior

Install the game, then start up.

### Actual Behavior

Game installs but crashes at startup.

@sSteamCmdForcePlatformType" = "windows"
Success! App '1007' already up to date.
ERROR! Failed to install app '374040' (No subscription)
First launch will throw some errors. Ignore them
:/home/container$ cd /home/container/dedicated_server; xvfb-run --auto-servernum wine pk_dedicated_server.exe -config server_config.json -log server.log
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
Application could not be started, or no application associated with the specifie
d file.
ShellExecuteEx failed: Environment variable not found.

X connection to :99 broken (explicit kill or server shutdown).
X connection to :99 broken (explicit kill or server shutdown).
X connection to :99 broken (explicit kill or server shutdown).
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

### Steps To Reproduce

Step 1. Install the game from the Egg
Step 2. start the game.

### Install logs

https://ptero.co/pofiwereje

**Comment by QuintenQVD0** [comment]
As mentioned in the readme you need an account that owns the game with steamguard off.
